name: build_cloud
on:
  push:
    branches:
      - standard
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: build_cloud
        run: rm -rf src/00
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: cloud
